import express from 'express';
import { electrical } from '../controllers/electrical.controller.js';

const router = express.Router();
// The exact "electrical/..." paths your React apiPath calls (mounted at /api/v1/electrical).
// Each path is forwarded to the core service by the controller.
router.all('/reports/break-down/cost', electrical);
router.all('/reports/break-down/date-wise', electrical);
router.all('/reports/break-down/department-wise', electrical);
router.all('/reports/break-down/machine-wise', electrical);
router.all('/reports/compressor-reading/date-wise', electrical);
router.all('/reports/compressor-reading/month-wise', electrical);
router.all('/reports/compressor-reading/performance', electrical);
router.all('/reports/cost', electrical);
router.all('/reports/daily-report', electrical);
router.all('/reports/day-wise-eb-reading/date-wise', electrical);
router.all('/reports/day-wise-eb-reading/ukg-date-wise', electrical);
router.all('/reports/day-wise-eb-reading/ukg-month-wise', electrical);
router.all('/reports/department-eb-reading/date-wise', electrical);
router.all('/reports/department-eb-reading/plant-wise', electrical);
router.all('/reports/department-eb-reading/power-group-wise', electrical);
router.all('/reports/diesel-consumption/date-wise', electrical);
router.all('/reports/eb-bill-monthly/date-wise', electrical);
router.all('/reports/eb-power-failure/date-wise', electrical);
router.all('/reports/eb-power-failure/individual', electrical);
router.all('/reports/electrical-eb-reading/date-wise', electrical);
router.all('/reports/generator-reading/date-wise', electrical);
router.all('/reports/generator-reading/month-wise', electrical);
router.all('/reports/next-service-consumption/date-wise', electrical);
router.all('/reports/next-service-consumption/department-wise', electrical);
router.all('/reports/next-service-consumption/item-stock', electrical);
router.all('/reports/next-service-consumption/item-wise', electrical);
router.all('/reports/next-service-consumption/last/item-wise', electrical);
router.all('/reports/next-service-consumption/last/machine-wise', electrical);
router.all('/reports/next-service-consumption/machine-wise', electrical);
router.all('/reports/next-service-schedule/date-wise', electrical);
router.all('/reports/next-service-schedule/department-wise', electrical);
router.all('/reports/next-service-schedule/machine-wise', electrical);
router.all('/reports/next-service-schedule/service-wise', electrical);
router.all('/reports/service-schedule/date-wise', electrical);
router.all('/reports/service-schedule/department-wise', electrical);
router.all('/reports/service-schedule/machine-wise', electrical);
router.all('/reports/service-schedule/pendings', electrical);
router.all('/reports/service-schedule/pendings-with-reason', electrical);
router.all('/reports/service-schedule/service-wise', electrical);
router.all('/reports/slot-wise-eb-reading/date-wise', electrical);
router.all('/reports/slot-wise-eb-reading/month-wise', electrical);
router.all('/reports/slot-wise-eb-reading/power-category-date-wise', electrical);
router.all('/reports/slot-wise-eb-reading/year-wise', electrical);
router.all('/reports/solar-reading/date-wise', electrical);
router.all('/reports/solar-reading/month-wise', electrical);
router.all('/reports/tonnage', electrical);
router.all('/reports/work-order/date-wise', electrical);
router.all('/reports/work-order/department-wise', electrical);
router.all('/reports/work-order/details/department-wise', electrical);
router.all('/reports/work-order/details/machine-wise', electrical);
router.all('/reports/work-order/details/machine-wise-breakdown', electrical);
router.all('/reports/work-order/details/service-wise', electrical);

export default router;
