import express from 'express';
import { electrical } from '../controllers/electrical.controller.js';
import { authenticate } from "../middleware/authMiddleware.js";

const router = express.Router();
// The exact "electrical/..." paths your React apiPath calls (mounted at /api/v1/electrical).
// Each path is forwarded to the core service by the controller.
router.all('/reports/break-down/cost',authenticate, electrical);
router.all('/reports/break-down/date-wise',authenticate, electrical);
router.all('/reports/break-down/department-wise',authenticate, electrical);
router.all('/reports/break-down/machine-wise',authenticate, electrical);
router.all('/reports/compressor-reading/date-wise',authenticate, electrical);
router.all('/reports/compressor-reading/month-wise',authenticate, electrical);
router.all('/reports/compressor-reading/performance',authenticate, electrical);
router.all('/reports/cost',authenticate, electrical);
router.all('/reports/daily-report',authenticate, electrical);
router.all('/reports/day-wise-eb-reading/date-wise',authenticate, electrical);
router.all('/reports/day-wise-eb-reading/ukg-date-wise',authenticate, electrical);
router.all('/reports/day-wise-eb-reading/ukg-month-wise',authenticate, electrical);
router.all('/reports/department-eb-reading/date-wise',authenticate, electrical);
router.all('/reports/department-eb-reading/plant-wise',authenticate, electrical);
router.all('/reports/department-eb-reading/power-group-wise',authenticate, electrical);
router.all('/reports/diesel-consumption/date-wise',authenticate, electrical);
router.all('/reports/eb-bill-monthly/date-wise',authenticate, electrical);
router.all('/reports/eb-power-failure/date-wise',authenticate, electrical);
router.all('/reports/eb-power-failure/individual',authenticate, electrical);
router.all('/reports/electrical-eb-reading/date-wise',authenticate, electrical);
router.all('/reports/generator-reading/date-wise',authenticate, electrical);
router.all('/reports/generator-reading/month-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/date-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/department-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/item-stock',authenticate, electrical);
router.all('/reports/next-service-consumption/item-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/last/item-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/last/machine-wise',authenticate, electrical);
router.all('/reports/next-service-consumption/machine-wise',authenticate, electrical);
router.all('/reports/next-service-schedule/date-wise',authenticate, electrical);
router.all('/reports/next-service-schedule/department-wise',authenticate, electrical);
router.all('/reports/next-service-schedule/machine-wise',authenticate, electrical);
router.all('/reports/next-service-schedule/service-wise',authenticate, electrical);
router.all('/reports/service-schedule/date-wise',authenticate, electrical);
router.all('/reports/service-schedule/department-wise',authenticate, electrical);
router.all('/reports/service-schedule/machine-wise',authenticate, electrical);
router.all('/reports/service-schedule/pendings',authenticate, electrical);
router.all('/reports/service-schedule/pendings-with-reason',authenticate, electrical);
router.all('/reports/service-schedule/service-wise',authenticate, electrical);
router.all('/reports/slot-wise-eb-reading/date-wise',authenticate, electrical);
router.all('/reports/slot-wise-eb-reading/month-wise',authenticate, electrical);
router.all('/reports/slot-wise-eb-reading/power-category-date-wise',authenticate, electrical);
router.all('/reports/slot-wise-eb-reading/year-wise',authenticate, electrical);
router.all('/reports/solar-reading/date-wise',authenticate, electrical);
router.all('/reports/solar-reading/month-wise',authenticate, electrical);
router.all('/reports/tonnage',authenticate, electrical);
router.all('/reports/work-order/date-wise',authenticate, electrical);
router.all('/reports/work-order/department-wise',authenticate, electrical);
router.all('/reports/work-order/details/department-wise',authenticate, electrical);
router.all('/reports/work-order/details/machine-wise',authenticate, electrical);
router.all('/reports/work-order/details/machine-wise-breakdown',authenticate, electrical);
router.all('/reports/work-order/details/service-wise',authenticate, electrical);

export default router;
