import express from 'express';
import badgeRouter from './badge.router.js';
import authRouter from './auth.router.js';
import companyRouter from './company.router.js';
import reportRouter from './report.router.js';
import cottonRouter from './cotton.router.js';
import documentRouter from './document.router.js';
import productionRouter from './production.router.js';
import payrollRouter from './payroll.router.js';
import allotmentRouter from './allotment.router.js';
import yarnRouter from './yarn.router.js';
import storesRouter from './stores.router.js';
import storeRouter from './store.router.js';
import hrmRouter from './hrm.router.js';
import gateRouter from './gate.router.js';
import financeRouter from './finance.router.js';
import bankRouter from './bank.router.js';
import maintenanceGroupRouter from './maintenanceGroup.router.js';
import departmentGroupRouter from './departmentGroup.router.js';
import departmentRouter from './department.router.js';
import approvalRouter from './approval.router.js';
import costHeadRouter from './costHead.router.js';
import stateRouter from './state.router.js';
import godownRouter from './godown.router.js';
import districtRouter from './district.router.js';
import costingMasterRouter from './costingMaster.router.js';
import itemCategoryRouter from './itemCategory.router.js';
import taxRouter from './tax.router.js';
import itemUomRouter from './itemUom.router.js';
import itemGroupRouter from './itemGroup.router.js';
import itemRouter from './item.router.js';
import machineRouter from './machine.router.js';
import machineMakeRouter from './machineMake.router.js';
import machineTypeRouter from './machineType.router.js';
import commonServiceActivityRouter from './commonServiceActivity.router.js';
import machineServiceScheduleRouter from './machineServiceSchedule.router.js';
import serviceActivityRouter from './serviceActivity.router.js';
import typeOfBreakdownRouter from './typeOfBreakdown.router.js';
import homeRouter from './home.router.js';
import graphRouter from './graph.router.js';
import wasteRouter from './waste.router.js';
import mechanicalRouter from './mechanical.router.js';
import electricalRouter from './electrical.router.js';
import weighbridgeRouter from './weighbridge.router.js';
import costingRouter from './costing.router.js';
import locationRouter from './location.router.js';
import notificationRouter from './notification.router.js';
import aiChatRouter from './aiChat.router.js';
import { authenticate } from '../middleware/authMiddleware.js';

const appRoutes = () => {
  const router = express.Router();

  // Public routes (no token required): login, fycode list, token create,
  // and the company list used to populate the login page dropdown.
  router.use('/auth', authRouter);
  router.use('/company', companyRouter);

  // Everything below this line requires a valid JWT.
  // router.use(authenticate);

  router.use('/badge', badgeRouter);
  router.use('/report', reportRouter);
  router.use('/cotton', cottonRouter);
  router.use('/document', documentRouter);
  router.use('/production', productionRouter);
  router.use('/payroll', payrollRouter);
  router.use('/allotment', allotmentRouter);
  router.use('/yarn', yarnRouter);
  router.use('/stores', storesRouter);
  router.use('/store', storeRouter);
  router.use('/hrm', hrmRouter);
  router.use('/gate', gateRouter);
  router.use('/finance', financeRouter);
  router.use('/bank', bankRouter);
  router.use('/maintenance-group', maintenanceGroupRouter);
  router.use('/department-group', departmentGroupRouter);
  router.use('/department', departmentRouter);
  router.use('/approval', approvalRouter);
  router.use('/cost-head', costHeadRouter);
  router.use('/state', stateRouter);
  router.use('/godown', godownRouter);
  router.use('/district', districtRouter);
  router.use('/costing-master', costingMasterRouter);
  router.use('/item-category', itemCategoryRouter);
  router.use('/tax', taxRouter);
  router.use('/item-uom', itemUomRouter);
  router.use('/item-group', itemGroupRouter);
  router.use('/item', itemRouter);
  router.use('/machine', machineRouter);
  router.use('/machine-make', machineMakeRouter);
  router.use('/machine-type', machineTypeRouter);
  router.use('/common-service-activity', commonServiceActivityRouter);
  router.use('/machine-service-schedule', machineServiceScheduleRouter);
  router.use('/service-activity', serviceActivityRouter);
  router.use('/type-of-breakdown', typeOfBreakdownRouter);
  router.use('/home', homeRouter);
  router.use('/graph', graphRouter);
  router.use('/waste', wasteRouter);
  router.use('/mechanical', mechanicalRouter);
  router.use('/electrical', electricalRouter);
  router.use('/weighbridge', weighbridgeRouter);
  router.use('/costing', costingRouter);
  router.use('/location', locationRouter);
  router.use('/notification', notificationRouter);
  router.use('/ai-chat', aiChatRouter);
  return router;
};
export default appRoutes;
