import express from 'express';
import badgeRouter from './badge.router.js';
import authRouter from './auth.router.js';
import companyRouter from './company.router.js';
import reportRouter from './report.router.js';
import cottonRouter from './cotton.router.js';
import documentRouter from './document.router.js';
import productionRouter from './production.router.js';
import payrollRouter from './payroll.router.js';
import allotmentRouter from './allotment.router.js';
import yarnRouter from './yarn.router.js';
import storesRouter from './stores.router.js';
import storeRouter from './store.router.js';
import hrmRouter from './hrm.router.js';
import gateRouter from './gate.router.js';
import financeRouter from './finance.router.js';
import bankRouter from './bank.router.js';
import maintenanceGroupRouter from './maintenanceGroup.router.js';
import departmentGroupRouter from './departmentGroup.router.js';
import departmentRouter from './department.router.js';
import approvalRouter from './approval.router.js';
import costHeadRouter from './costHead.router.js';
import stateRouter from './state.router.js';
import godownRouter from './godown.router.js';
import districtRouter from './district.router.js';
import costingMasterRouter from './costingMaster.router.js';
import itemCategoryRouter from './itemCategory.router.js';
import taxRouter from './tax.router.js';
import itemUomRouter from './itemUom.router.js';
import itemUsageTypeRouter from './itemUsageType.router.js';
import itemGroupRouter from './itemGroup.router.js';
import itemRouter from './item.router.js';
import machineRouter from './machine.router.js';
import machineMakeRouter from './machineMake.router.js';
import machineTypeRouter from './machineType.router.js';
import vehicleMakeRouter from './vehicleMake.router.js';
import vehicleCapacityRouter from './vehicleCapacity.router.js';
import vehicleRouter from './vehicle.router.js';
import agentRouter from './agent.router.js';
import customerApproveRouter from './customerApprove.router.js';
import customerRouter from './customer.router.js';
import customerTypeRouter from './customerType.router.js';
import supplierApproveRouter from './supplierApprove.router.js';
import supplierRouter from './supplier.router.js';
import transporterRouter from './transporter.router.js';
import rawMaterialTypeRouter from './rawMaterialType.router.js';
import rawMaterialRouter from './rawMaterial.router.js';
import cottonCountRouter from './cottonCount.router.js';
import countGroupRouter from './countGroup.router.js';
import cottonPackingMaterialRouter from './cottonPackingMaterial.router.js';
import stationRouter from './station.router.js';
import cqtParameterRouter from './cqtParameter.router.js';
import cqtStdRouter from './cqtStd.router.js';
import goodsInOutTypeRouter from './goodsInOutType.router.js';
import materialTypeRouter from './materialType.router.js';
import accountGroupRouter from './accountGroup.router.js';
import cottonPurchaseOrderRouter from './cottonPurchaseOrder.router.js';
import cottonPurchaseOrderAmendmentRouter from './cottonPurchaseOrderAmendment.router.js';
import cottonPurchaseOrderCancelRouter from './cottonPurchaseOrderCancel.router.js';
import cottonQualityTestApprovalRouter from './cottonQualityTestApproval.router.js';
import cottonGodownTransferRouter from './cottonGodownTransfer.router.js';
import cottonArrivalRouter from './cottonArrival.router.js';
import cottonWeighmentRouter from './cottonWeighment.router.js';
import cottonWeighmentApprovalRouter from './cottonWeighmentApproval.router.js';
import cottonQualityTestRouter from './cottonQualityTest.router.js';
import cottonLotApprovalRouter from './cottonLotApproval.router.js';
import cottonMixingIssueRequisitionRouter from './cottonMixingIssueRequisition.router.js';
import cottonIssueRouter from './cottonIssue.router.js';
import cottonSalesRouter from './cottonSales.router.js';
import cottonSalesReturnRouter from './cottonSalesReturn.router.js';
import cottonRejectRouter from './cottonReject.router.js';
import cottonRejectLotPendingRouter from './cottonRejectLotPending.router.js';
import cottonAllowanceRouter from './cottonAllowance.router.js';
import cottonWeightApprovalRouter from './cottonWeightApproval.router.js';
import itemRequisitionRouter from './itemRequisition.router.js';
import itemRequisitionAdjustmentRouter from './itemRequisitionAdjustment.router.js';
import itemIndentRouter from './itemIndent.router.js';
import purchaseOrderRouter from './purchaseOrder.router.js';
import serviceOrderExpensesRouter from './serviceOrderExpenses.router.js';
import commonServiceActivityRouter from './commonServiceActivity.router.js';
import machineServiceScheduleRouter from './machineServiceSchedule.router.js';
import serviceActivityRouter from './serviceActivity.router.js';
import typeOfBreakdownRouter from './typeOfBreakdown.router.js';
import homeRouter from './home.router.js';
import graphRouter from './graph.router.js';
import wasteRouter from './waste.router.js';
import mechanicalRouter from './mechanical.router.js';
import electricalRouter from './electrical.router.js';
import weighbridgeRouter from './weighbridge.router.js';
import costingRouter from './costing.router.js';
import locationRouter from './location.router.js';
import notificationRouter from './notification.router.js';
import aiChatRouter from './aiChat.router.js';
import gstRouter from './gst.router.js';
import { authenticate } from '../middleware/authMiddleware.js';

const appRoutes = () => {
  const router = express.Router();

  // Public routes (no token required): login, fycode list, token create,
  // and the company list used to populate the login page dropdown.
  router.use('/auth', authRouter);
  router.use('/company', companyRouter);

  // Everything below this line requires a valid JWT.
  // router.use(authenticate);

  router.use('/badge', badgeRouter);
  router.use('/report', reportRouter);
  router.use('/cotton', cottonRouter);
  router.use('/document', documentRouter);
  router.use('/production', productionRouter);
  router.use('/payroll', payrollRouter);
  router.use('/allotment', allotmentRouter);
  router.use('/yarn', yarnRouter);
  router.use('/stores', storesRouter);
  router.use('/store', storeRouter);
  router.use('/hrm', hrmRouter);
  router.use('/gate', gateRouter);
  router.use('/finance', financeRouter);
  router.use('/bank', bankRouter);
  router.use('/maintenance-group', maintenanceGroupRouter);
  router.use('/department-group', departmentGroupRouter);
  router.use('/department', departmentRouter);
  router.use('/approval', approvalRouter);
  router.use('/cost-head', costHeadRouter);
  router.use('/state', stateRouter);
  router.use('/godown', godownRouter);
  router.use('/district', districtRouter);
  router.use('/costing-master', costingMasterRouter);
  router.use('/item-category', itemCategoryRouter);
  router.use('/tax', taxRouter);
  router.use('/item-uom', itemUomRouter);
  router.use('/item-usage-type', itemUsageTypeRouter);
  router.use('/item-group', itemGroupRouter);
  router.use('/item', itemRouter);
  router.use('/machine', machineRouter);
  router.use('/machine-make', machineMakeRouter);
  router.use('/machine-type', machineTypeRouter);
  router.use('/vehicle-make', vehicleMakeRouter);
  router.use('/vehicle-capacity', vehicleCapacityRouter);
  router.use('/vehicle', vehicleRouter);
  router.use('/agent', agentRouter);
  router.use('/customer-approve', customerApproveRouter);
  router.use('/customer', customerRouter);
  router.use('/customer-type', customerTypeRouter);
  router.use('/supplier-approve', supplierApproveRouter);
  router.use('/supplier', supplierRouter);
  router.use('/transporter', transporterRouter);
  router.use('/raw-material-type', rawMaterialTypeRouter);
  router.use('/raw-material', rawMaterialRouter);
  router.use('/cotton-count', cottonCountRouter);
  router.use('/count-group', countGroupRouter);
  router.use('/cotton-packing-material', cottonPackingMaterialRouter);
  router.use('/station', stationRouter);
  router.use('/cqt-parameter', cqtParameterRouter);
  router.use('/cqt-std', cqtStdRouter);
  router.use('/goods-in-out-type', goodsInOutTypeRouter);
  router.use('/material-type', materialTypeRouter);
  router.use('/account-group', accountGroupRouter);
  router.use('/cotton-purchase-order', cottonPurchaseOrderRouter);
  router.use('/cotton-purchase-order-amendment', cottonPurchaseOrderAmendmentRouter);
  router.use('/cotton-purchase-order-cancel', cottonPurchaseOrderCancelRouter);
  router.use('/cotton-quality-test-approval', cottonQualityTestApprovalRouter);
  router.use('/cotton-godown-transfer', cottonGodownTransferRouter);
  router.use('/cotton-arrival', cottonArrivalRouter);
  router.use('/cotton-weighment', cottonWeighmentRouter);
  router.use('/cotton-weighment-approval', cottonWeighmentApprovalRouter);
  router.use('/cotton-quality-test', cottonQualityTestRouter);
  router.use('/cotton-lot-approval', cottonLotApprovalRouter);
  router.use('/cotton-mixing-issue-requisition', cottonMixingIssueRequisitionRouter);
  router.use('/cotton-issue', cottonIssueRouter);
  router.use('/cotton-sales', cottonSalesRouter);
  router.use('/cotton-sales-return', cottonSalesReturnRouter);
  router.use('/cotton-reject', cottonRejectRouter);
  router.use('/cotton-reject-lot-pending', cottonRejectLotPendingRouter);
  router.use('/cotton-allowance', cottonAllowanceRouter);
  router.use('/cotton-weight-approval', cottonWeightApprovalRouter);
  router.use('/item-requisition', itemRequisitionRouter);
  router.use('/item-requisition-adjustment', itemRequisitionAdjustmentRouter);
  router.use('/item-indent', itemIndentRouter);
  router.use('/purchase-order', purchaseOrderRouter);
  router.use('/service-order-expenses', serviceOrderExpensesRouter);
  router.use('/common-service-activity', commonServiceActivityRouter);
  router.use('/machine-service-schedule', machineServiceScheduleRouter);
  router.use('/service-activity', serviceActivityRouter);
  router.use('/type-of-breakdown', typeOfBreakdownRouter);
  router.use('/home', homeRouter);
  router.use('/graph', graphRouter);
  router.use('/waste', wasteRouter);
  router.use('/mechanical', mechanicalRouter);
  router.use('/electrical', electricalRouter);
  router.use('/weighbridge', weighbridgeRouter);
  router.use('/costing', costingRouter);
  router.use('/location', locationRouter);
  router.use('/notification', notificationRouter);
  router.use('/ai-chat', aiChatRouter);
  router.use('/gst', gstRouter);
  return router;
};
export default appRoutes;
