import express from 'express';
import badgeRouter from './badge.router.js';
import authRouter from './auth.router.js';
import companyRouter from './company.router.js';
import reportRouter from './report.router.js';
import cottonRouter from './cotton.router.js';
import documentRouter from './document.router.js';
import productionRouter from './production.router.js';
import payrollRouter from './payroll.router.js';
import allotmentRouter from './allotment.router.js';
import yarnRouter from './yarn.router.js';
import storesRouter from './stores.router.js';
import storeRouter from './store.router.js';
import hrmRouter from './hrm.router.js';
import gateRouter from './gate.router.js';
import financeRouter from './finance.router.js';
import bankRouter from './bank.router.js';
import maintenanceGroupRouter from './maintenanceGroup.router.js';
import plantGroupRouter from './plantGroup.router.js';
import solarGroupRouter from './solarGroup.router.js';
import solarLocationRouter from './solarLocation.router.js';
import ebMeterRouter from './ebMeter.router.js';
import plantMasterRouter from './plantMaster.router.js';
import slotRouter from './slot.router.js';
import generatorMachineGroupRouter from './generatorMachineGroup.router.js';
import powerCategoryRouter from './powerCategory.router.js';
import compressorGroupMasterRouter from './compressorGroupMaster.router.js';
import machineGroupRouter from './machineGroup.router.js';
import ebRateRouter from './ebRate.router.js';
import electricalScheduleRouter from './electricalSchedule.router.js';
import breakdownRouter from './breakdown.router.js';
import workOrderRouter from './workOrder.router.js';
import empEngagedRouter from './empEngaged.router.js';
import powerFailureRouter from './powerFailure.router.js';
import electricalReadingRouter from './electricalReading.router.js';
import machineTapeCutRouter from './machineTapeCut.router.js';
import maintenanceBuffingRouter from './maintenanceBuffing.router.js';
import maintenanceDesignationRouter from './maintenanceDesignation.router.js';
import departmentGroupRouter from './departmentGroup.router.js';
import departmentRouter from './department.router.js';
import approvalRouter from './approval.router.js';
import costHeadRouter from './costHead.router.js';
import stateRouter from './state.router.js';
import godownRouter from './godown.router.js';
import districtRouter from './district.router.js';
import costingMasterRouter from './costingMaster.router.js';
import itemCategoryRouter from './itemCategory.router.js';
import taxRouter from './tax.router.js';
import itemUomRouter from './itemUom.router.js';
import itemUsageTypeRouter from './itemUsageType.router.js';
import itemGroupRouter from './itemGroup.router.js';
import itemRouter from './item.router.js';
import machineRouter from './machine.router.js';
import machineMakeRouter from './machineMake.router.js';
import machineTypeRouter from './machineType.router.js';
import vehicleMakeRouter from './vehicleMake.router.js';
import vehicleCapacityRouter from './vehicleCapacity.router.js';
import vehicleRouter from './vehicle.router.js';
import vehicleExpensesGroupRouter from './vehicleExpensesGroup.router.js';
import vehicleExpensesRouter from './vehicleExpenses.router.js';
import vehicleExpensesEntryRouter from './vehicleExpensesEntry.router.js';
import agentRouter from './agent.router.js';
import customerApproveRouter from './customerApprove.router.js';
import customerRouter from './customer.router.js';
import customerTypeRouter from './customerType.router.js';
import supplierApproveRouter from './supplierApprove.router.js';
import supplierRouter from './supplier.router.js';
import transporterRouter from './transporter.router.js';
import rawMaterialTypeRouter from './rawMaterialType.router.js';
import rawMaterialRouter from './rawMaterial.router.js';
import cottonCountRouter from './cottonCount.router.js';
import countGroupRouter from './countGroup.router.js';
import countNameRouter from './countName.router.js';
import countTypeRouter from './countType.router.js';
import lotNoRouter from './lotNo.router.js';
import tipColourRouter from './tipColour.router.js';
import bagColourRouter from './bagColour.router.js';
import salesTypeRouter from './salesType.router.js';
import taxTypeRouter from './taxType.router.js';
import otherChargesRouter from './otherCharges.router.js';
import cottonPackingMaterialRouter from './cottonPackingMaterial.router.js';
import stationRouter from './station.router.js';
import cqtParameterRouter from './cqtParameter.router.js';
import cqtStdRouter from './cqtStd.router.js';
import goodsInOutTypeRouter from './goodsInOutType.router.js';
import materialTypeRouter from './materialType.router.js';
import wasteItemGroupRouter from './wasteItemGroup.router.js';
import mixingNameRouter from './mixingName.router.js';
import stoppageGroupRouter from './stoppageGroup.router.js';
import stoppageReasonRouter from './stoppageReason.router.js';
import cardingMachineSettingRouter from './cardingMachineSetting.router.js';
import cardingProductionRouter from './cardingProduction.router.js';
import drawingMachineSettingRouter from './drawingMachineSetting.router.js';
import drawingProductionRouter from './drawingProduction.router.js';
import unilapMachineSettingRouter from './unilapMachineSetting.router.js';
import unilapProductionRouter from './unilapProduction.router.js';
import comberMachineSettingRouter from './comberMachineSetting.router.js';
import comberProductionRouter from './comberProduction.router.js';
import finisherDrawingMachineSettingRouter from './finisherDrawingMachineSetting.router.js';
import finisherDrawingProductionRouter from './finisherDrawingProduction.router.js';
import simplexMachineSettingRouter from './simplexMachineSetting.router.js';
import simplexProductionRouter from './simplexProduction.router.js';
import spinningCountSettingRouter from './spinningCountSetting.router.js';
import spinningFrameSettingRouter from './spinningFrameSetting.router.js';
import spinningProductionRouter from './spinningProduction.router.js';
import spinningStopReasonRouter from './spinningStopReason.router.js';
import autoconerCountSettingRouter from './autoconerCountSetting.router.js';
import autoconerMachineSettingRouter from './autoconerMachineSetting.router.js';
import autoconerProductionRouter from './autoconerProduction.router.js';
import autoconerCountWiseProductionRouter from './autoconerCountWiseProduction.router.js';
import ycpProductionRouter from './ycpProduction.router.js';
import oeCountSettingRouter from './oeCountSetting.router.js';
import oeFrameSettingRouter from './oeFrameSetting.router.js';
import oeProductionRouter from './oeProduction.router.js';
import prodnEmpEngagedRouter from './prodnEmpEngaged.router.js';
import productionDataDownloadRouter from './productionDataDownload.router.js';
import wasteItemRouter from './wasteItem.router.js';
import usableWasteItemRouter from './usableWasteItem.router.js';
import wasteProductionRouter from './wasteProduction.router.js';
import usableWasteProductionRouter from './usableWasteProduction.router.js';
import usableWasteIssueRouter from './usableWasteIssue.router.js';
import wasteDCRouter from './wasteDC.router.js';
import wasteInvoiceRouter from './wasteInvoice.router.js';
import wasteInvoiceApprovalRouter from './wasteInvoiceApproval.router.js';
import scrapInvoiceRouter from './scrapInvoice.router.js';
import accountGroupRouter from './accountGroup.router.js';
import cottonPurchaseOrderRouter from './cottonPurchaseOrder.router.js';
import cottonPurchaseOrderAmendmentRouter from './cottonPurchaseOrderAmendment.router.js';
import cottonPurchaseOrderCancelRouter from './cottonPurchaseOrderCancel.router.js';
import cottonQualityTestApprovalRouter from './cottonQualityTestApproval.router.js';
import cottonGodownTransferRouter from './cottonGodownTransfer.router.js';
import cottonArrivalRouter from './cottonArrival.router.js';
import cottonWeighmentRouter from './cottonWeighment.router.js';
import cottonWeighmentApprovalRouter from './cottonWeighmentApproval.router.js';
import cottonQualityTestRouter from './cottonQualityTest.router.js';
import cottonLotApprovalRouter from './cottonLotApproval.router.js';
import cottonMixingIssueRequisitionRouter from './cottonMixingIssueRequisition.router.js';
import cottonIssueRouter from './cottonIssue.router.js';
import cottonSalesRouter from './cottonSales.router.js';
import cottonSalesReturnRouter from './cottonSalesReturn.router.js';
import cottonRejectRouter from './cottonReject.router.js';
import cottonRejectLotPendingRouter from './cottonRejectLotPending.router.js';
import cottonAllowanceRouter from './cottonAllowance.router.js';
import cottonWeightApprovalRouter from './cottonWeightApproval.router.js';
import itemRequisitionRouter from './itemRequisition.router.js';
import itemRequisitionAdjustmentRouter from './itemRequisitionAdjustment.router.js';
import itemIndentRouter from './itemIndent.router.js';
import purchaseOrderRouter from './purchaseOrder.router.js';
import inwardRouter from './inward.router.js';
import companyVisitorsRouter from './companyVisitors.router.js';
import vehicleInOutRouter from './vehicleInOut.router.js';
import gradeRouter from './grade.router.js';
import employmentRouter from './employment.router.js';
import payHeadRouter from './payHead.router.js';
import holidayRouter from './holiday.router.js';
import manualEntryReasonRouter from './manualEntryReason.router.js';
import routeRouter from './route.router.js';
import routeVehicleRouter from './routeVehicle.router.js';
import purchaseReturnRouter from './purchaseReturn.router.js';
import purchaseOrderPrintRouter from './purchaseOrderPrint.router.js';
import serviceOrderExpensesRouter from './serviceOrderExpenses.router.js';
import commonServiceActivityRouter from './commonServiceActivity.router.js';
import machineServiceScheduleRouter from './machineServiceSchedule.router.js';
import serviceActivityRouter from './serviceActivity.router.js';
import typeOfBreakdownRouter from './typeOfBreakdown.router.js';
import homeRouter from './home.router.js';
import graphRouter from './graph.router.js';
import wasteRouter from './waste.router.js';
import mechanicalRouter from './mechanical.router.js';
import electricalRouter from './electrical.router.js';
import weighbridgeRouter from './weighbridge.router.js';
import costingRouter from './costing.router.js';
import locationRouter from './location.router.js';
import notificationRouter from './notification.router.js';
import aiChatRouter from './aiChat.router.js';
import gstRouter from './gst.router.js';
import { authenticate } from '../middleware/authMiddleware.js';

const appRoutes = () => {
  const router = express.Router();

  // Public routes (no token required): login, fycode list, token create,
  // and the company list used to populate the login page dropdown.
  router.use('/auth', authRouter);
  router.use('/company', companyRouter);

  // Everything below this line requires a valid JWT.
  // router.use(authenticate);

  router.use('/badge', badgeRouter);
  router.use('/report', reportRouter);
  router.use('/cotton', cottonRouter);
  router.use('/document', documentRouter);
  router.use('/production', productionRouter);
  router.use('/payroll', payrollRouter);
  router.use('/allotment', allotmentRouter);
  router.use('/yarn', yarnRouter);
  router.use('/stores', storesRouter);
  router.use('/store', storeRouter);
  router.use('/hrm', hrmRouter);
  router.use('/gate', gateRouter);
  router.use('/company-visitors', companyVisitorsRouter);
  router.use('/vehicle-in-out', vehicleInOutRouter);
  router.use('/grade', gradeRouter);
  router.use('/employment', employmentRouter);
  router.use('/pay-head', payHeadRouter);
  router.use('/holiday', holidayRouter);
  router.use('/manual-entry-reason', manualEntryReasonRouter);
  router.use('/route', routeRouter);
  router.use('/route-vehicle', routeVehicleRouter);
  router.use('/finance', financeRouter);
  router.use('/bank', bankRouter);
  router.use('/maintenance-group', maintenanceGroupRouter);
  router.use('/plant-group', plantGroupRouter);
  router.use('/solar-group', solarGroupRouter);
  router.use('/solar-location', solarLocationRouter);
  router.use('/eb-meter', ebMeterRouter);
  router.use('/plant-master', plantMasterRouter);
  router.use('/slot', slotRouter);
  router.use('/generator-machine-group', generatorMachineGroupRouter);
  router.use('/power-category', powerCategoryRouter);
  router.use('/compressor-group-master', compressorGroupMasterRouter);
  router.use('/machine-group', machineGroupRouter);
  router.use('/eb-rate', ebRateRouter);
  router.use('/electrical-schedule', electricalScheduleRouter);
  router.use('/breakdown', breakdownRouter);
  router.use('/work-order', workOrderRouter);
  router.use('/emp-engaged', empEngagedRouter);
  router.use('/power-failure', powerFailureRouter);
  router.use('/electrical-reading', electricalReadingRouter);
  router.use('/machine-tape-cut', machineTapeCutRouter);
  router.use('/maintenance-buffing', maintenanceBuffingRouter);
  router.use('/maintenance-designation', maintenanceDesignationRouter);
  router.use('/department-group', departmentGroupRouter);
  router.use('/department', departmentRouter);
  router.use('/approval', approvalRouter);
  router.use('/cost-head', costHeadRouter);
  router.use('/state', stateRouter);
  router.use('/godown', godownRouter);
  router.use('/district', districtRouter);
  router.use('/costing-master', costingMasterRouter);
  router.use('/item-category', itemCategoryRouter);
  router.use('/tax', taxRouter);
  router.use('/item-uom', itemUomRouter);
  router.use('/item-usage-type', itemUsageTypeRouter);
  router.use('/item-group', itemGroupRouter);
  router.use('/item', itemRouter);
  router.use('/machine', machineRouter);
  router.use('/machine-make', machineMakeRouter);
  router.use('/machine-type', machineTypeRouter);
  router.use('/vehicle-make', vehicleMakeRouter);
  router.use('/vehicle-capacity', vehicleCapacityRouter);
  router.use('/vehicle-expenses-group', vehicleExpensesGroupRouter);
  router.use('/vehicle-expenses-entry', vehicleExpensesEntryRouter);
  router.use('/vehicle-expenses', vehicleExpensesRouter);
  router.use('/vehicle', vehicleRouter);
  router.use('/agent', agentRouter);
  router.use('/customer-approve', customerApproveRouter);
  router.use('/customer', customerRouter);
  router.use('/customer-type', customerTypeRouter);
  router.use('/supplier-approve', supplierApproveRouter);
  router.use('/supplier', supplierRouter);
  router.use('/transporter', transporterRouter);
  router.use('/raw-material-type', rawMaterialTypeRouter);
  router.use('/raw-material', rawMaterialRouter);
  router.use('/cotton-count', cottonCountRouter);
  router.use('/count-group', countGroupRouter);
  router.use('/count-name', countNameRouter);
  router.use('/count-type', countTypeRouter);
  router.use('/lot-no', lotNoRouter);
  router.use('/tip-colour', tipColourRouter);
  router.use('/bag-colour', bagColourRouter);
  router.use('/sales-type', salesTypeRouter);
  router.use('/tax-type', taxTypeRouter);
  router.use('/other-charges', otherChargesRouter);
  router.use('/cotton-packing-material', cottonPackingMaterialRouter);
  router.use('/station', stationRouter);
  router.use('/cqt-parameter', cqtParameterRouter);
  router.use('/cqt-std', cqtStdRouter);
  router.use('/goods-in-out-type', goodsInOutTypeRouter);
  router.use('/material-type', materialTypeRouter);
  router.use('/waste-item-group', wasteItemGroupRouter);
  router.use('/mixing-name', mixingNameRouter);
  router.use('/stoppage-group', stoppageGroupRouter);
  router.use('/stoppage-reason', stoppageReasonRouter);
  router.use('/carding-machine-setting', cardingMachineSettingRouter);
  router.use('/carding-production', cardingProductionRouter);
  router.use('/drawing-machine-setting', drawingMachineSettingRouter);
  router.use('/drawing-production', drawingProductionRouter);
  router.use('/unilap-machine-setting', unilapMachineSettingRouter);
  router.use('/unilap-production', unilapProductionRouter);
  router.use('/comber-machine-setting', comberMachineSettingRouter);
  router.use('/comber-production', comberProductionRouter);
  router.use('/finisher-drawing-machine-setting', finisherDrawingMachineSettingRouter);
  router.use('/finisher-drawing-production', finisherDrawingProductionRouter);
  router.use('/simplex-machine-setting', simplexMachineSettingRouter);
  router.use('/simplex-production', simplexProductionRouter);
  router.use('/spinning-count-setting', spinningCountSettingRouter);
  router.use('/spinning-frame-setting', spinningFrameSettingRouter);
  router.use('/spinning-production', spinningProductionRouter);
  router.use('/spinning-stop-reason', spinningStopReasonRouter);
  router.use('/autoconer-count-setting', autoconerCountSettingRouter);
  router.use('/autoconer-machine-setting', autoconerMachineSettingRouter);
  router.use('/autoconer-production', autoconerProductionRouter);
  router.use('/autoconer-count-wise-production', autoconerCountWiseProductionRouter);
  router.use('/ycp-production', ycpProductionRouter);
  router.use('/oe-count-setting', oeCountSettingRouter);
  router.use('/oe-frame-setting', oeFrameSettingRouter);
  router.use('/oe-production', oeProductionRouter);
  router.use('/prodn-emp-engaged', prodnEmpEngagedRouter);
  router.use('/production-data-download', productionDataDownloadRouter);
  router.use('/waste-item', wasteItemRouter);
  router.use('/usable-waste-item', usableWasteItemRouter);
  router.use('/waste-production', wasteProductionRouter);
  router.use('/usable-waste-production', usableWasteProductionRouter);
  router.use('/usable-waste-issue', usableWasteIssueRouter);
  router.use('/waste-dc', wasteDCRouter);
  router.use('/waste-invoice', wasteInvoiceRouter);
  router.use('/waste-invoice-approval', wasteInvoiceApprovalRouter);
  router.use('/scrap-invoice', scrapInvoiceRouter);
  router.use('/account-group', accountGroupRouter);
  router.use('/cotton-purchase-order', cottonPurchaseOrderRouter);
  router.use('/cotton-purchase-order-amendment', cottonPurchaseOrderAmendmentRouter);
  router.use('/cotton-purchase-order-cancel', cottonPurchaseOrderCancelRouter);
  router.use('/cotton-quality-test-approval', cottonQualityTestApprovalRouter);
  router.use('/cotton-godown-transfer', cottonGodownTransferRouter);
  router.use('/cotton-arrival', cottonArrivalRouter);
  router.use('/cotton-weighment', cottonWeighmentRouter);
  router.use('/cotton-weighment-approval', cottonWeighmentApprovalRouter);
  router.use('/cotton-quality-test', cottonQualityTestRouter);
  router.use('/cotton-lot-approval', cottonLotApprovalRouter);
  router.use('/cotton-mixing-issue-requisition', cottonMixingIssueRequisitionRouter);
  router.use('/cotton-issue', cottonIssueRouter);
  router.use('/cotton-sales', cottonSalesRouter);
  router.use('/cotton-sales-return', cottonSalesReturnRouter);
  router.use('/cotton-reject', cottonRejectRouter);
  router.use('/cotton-reject-lot-pending', cottonRejectLotPendingRouter);
  router.use('/cotton-allowance', cottonAllowanceRouter);
  router.use('/cotton-weight-approval', cottonWeightApprovalRouter);
  router.use('/item-requisition', itemRequisitionRouter);
  router.use('/item-requisition-adjustment', itemRequisitionAdjustmentRouter);
  router.use('/item-indent', itemIndentRouter);
  router.use('/purchase-order', purchaseOrderRouter);
  router.use('/inward', inwardRouter);
  router.use('/purchase-return', purchaseReturnRouter);
  router.use('/purchase-order-print', purchaseOrderPrintRouter);
  router.use('/service-order-expenses', serviceOrderExpensesRouter);
  router.use('/common-service-activity', commonServiceActivityRouter);
  router.use('/machine-service-schedule', machineServiceScheduleRouter);
  router.use('/service-activity', serviceActivityRouter);
  router.use('/type-of-breakdown', typeOfBreakdownRouter);
  router.use('/home', homeRouter);
  router.use('/graph', graphRouter);
  router.use('/waste', wasteRouter);
  router.use('/mechanical', mechanicalRouter);
  router.use('/electrical', electricalRouter);
  router.use('/weighbridge', weighbridgeRouter);
  router.use('/costing', costingRouter);
  router.use('/location', locationRouter);
  router.use('/notification', notificationRouter);
  router.use('/ai-chat', aiChatRouter);
  router.use('/gst', gstRouter);
  return router;
};
export default appRoutes;
