import express from 'express';
import { mechanical } from '../controllers/mechanical.controller.js';
import { authenticate } from "../middleware/authMiddleware.js";

const router = express.Router();
// The exact "mechanical/..." paths your React apiPath calls (mounted at /api/v1/mechanical).
// Each path is forwarded to the core service by the controller.
router.all('/reports/break-down/cost',authenticate, mechanical);
router.all('/reports/break-down/options',authenticate, mechanical);
router.all('/reports/break-down/department-wise-consolidate',authenticate, mechanical);
router.all('/reports/break-down-month-wise/options',authenticate, mechanical);
router.all('/reports/break-down-month-wise',authenticate, mechanical);
router.all('/reports/break-down-year-wise',authenticate, mechanical);
router.all('/reports/break-down/date-wise',authenticate, mechanical);
router.all('/reports/break-down/department-wise',authenticate, mechanical);
router.all('/reports/break-down/machine-wise',authenticate, mechanical);
router.all('/reports/cost',authenticate, mechanical);
router.all('/reports/daily-report/options',authenticate, mechanical);
router.all('/reports/daily-report',authenticate, mechanical);
router.all('/reports/machine-buffing/date-wise',authenticate, mechanical);
router.all('/reports/machine-buffing/detail',authenticate, mechanical);
router.all('/reports/machine-buffing/pending',authenticate, mechanical);
router.all('/reports/machine-buffing/options',authenticate, mechanical);
router.all('/reports/machine-details/options',authenticate, mechanical);
router.all('/reports/machine-details',authenticate, mechanical);
router.all('/reports/machine-doc-print/options',authenticate, mechanical);
router.all('/reports/machine-doc-print/machines',authenticate, mechanical);
router.all('/reports/machine-doc-print',authenticate, mechanical);
router.all('/reports/type-of-breakdown/options',authenticate, mechanical);
router.all('/reports/type-of-breakdown',authenticate, mechanical);
router.all('/reports/machine-tape-cut/date-wise',authenticate, mechanical);
router.all('/reports/machine-tape-cut/department-wise',authenticate, mechanical);
router.all('/reports/machine-tape-cut/item-wise',authenticate, mechanical);
router.all('/reports/machine-tape-cut/machine-wise',authenticate, mechanical);
router.all('/reports/machine-tape-cut/options',authenticate, mechanical);
router.all('/reports/maintenance-life-span',authenticate, mechanical);
router.all('/reports/next-service-consumption/date-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/department-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/item-stock',authenticate, mechanical);
router.all('/reports/next-service-consumption/options',authenticate, mechanical);
router.all('/reports/next-service-consumption/item-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/last/item-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/last/machine-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/last/breakdown-item-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/last/breakdown-machine-wise',authenticate, mechanical);
router.all('/reports/next-service-consumption/machine-wise',authenticate, mechanical);
router.all('/reports/next-service-schedule/date-wise',authenticate, mechanical);
router.all('/reports/next-service-schedule/options',authenticate, mechanical);
router.all('/reports/next-service-schedule/over-all',authenticate, mechanical);
router.all('/reports/next-service-schedule/department-wise',authenticate, mechanical);
router.all('/reports/next-service-schedule/machine-wise',authenticate, mechanical);
router.all('/reports/next-service-schedule/service-wise',authenticate, mechanical);
router.all('/reports/service-schedule/date-wise',authenticate, mechanical);
router.all('/reports/service-schedule/department-wise',authenticate, mechanical);
router.all('/reports/service-schedule/machine-wise',authenticate, mechanical);
router.all('/reports/service-schedule/pendings',authenticate, mechanical);
router.all('/reports/service-schedule/pendings-with-reason',authenticate, mechanical);
router.all('/reports/service-schedule/options',authenticate, mechanical);
router.all('/reports/service-schedule/last-maintenance',authenticate, mechanical);
router.all('/reports/service-schedule/overall-pendings',authenticate, mechanical);
router.all('/reports/service-schedule/tonnage-summary',authenticate, mechanical);
router.all('/reports/service-schedule/tonnage-pendings',authenticate, mechanical);
router.all('/reports/service-schedule/service-wise',authenticate, mechanical);
router.all('/reports/tonnage',authenticate, mechanical);
router.all('/reports/work-order/options',authenticate, mechanical);
router.all('/reports/work-order/date-wise',authenticate, mechanical);
router.all('/reports/work-order/department-wise',authenticate, mechanical);
router.all('/reports/work-order/details/department-wise',authenticate, mechanical);
router.all('/reports/work-order/details/machine-wise',authenticate, mechanical);
router.all('/reports/work-order/details/machine-wise-breakdown',authenticate, mechanical);
router.all('/reports/work-order/details/service-wise',authenticate, mechanical);

export default router;
