import express from 'express';
import { production } from '../controllers/production.controller.js';
import { authenticate } from "../middleware/authMiddleware.js";

const router = express.Router();
// The exact "production/..." paths your React apiPath calls (mounted at /api/v1/production).
// Each path is forwarded to the core service by the controller.
router.all('/reports/carding/machine-wise',authenticate, production);
router.all('/reports/carding/stoppage',authenticate, production);
router.all('/reports/carding/summary',authenticate, production);
router.all('/reports/carding/shift-wise',authenticate, production);
router.all('/reports/carding/shift-wise-details',authenticate, production);
router.all('/reports/carding/mix-wise',authenticate, production);
router.all('/reports/carding/employee-performance',authenticate, production);
router.all('/reports/drawing/shift-wise',authenticate, production);
router.all('/reports/drawing/shift-wise-details',authenticate, production);
router.all('/reports/drawing/mix-wise',authenticate, production);
router.all('/reports/drawing/employee-performance',authenticate, production);
router.all('/reports/unilap/shift-wise',authenticate, production);
router.all('/reports/unilap/shift-wise-details',authenticate, production);
router.all('/reports/unilap/mix-wise',authenticate, production);
router.all('/reports/unilap/employee-performance',authenticate, production);
router.all('/reports/comber/employee-performance',authenticate, production);
router.all('/reports/comber/shift-wise-details',authenticate, production);
router.all('/reports/comber/mix-wise',authenticate, production);
router.all('/reports/comber/machine-wise',authenticate, production);
router.all('/reports/comber/shift-wise',authenticate, production);
router.all('/reports/comber/stoppage',authenticate, production);
router.all('/reports/comber/summary',authenticate, production);
router.all('/reports/drawing/machine-wise',authenticate, production);
router.all('/reports/drawing/stoppage',authenticate, production);
router.all('/reports/drawing/summary',authenticate, production);
router.all('/reports/finisher-drawing/employee-performance',authenticate, production);
router.all('/reports/finisher-drawing/shift-wise-details',authenticate, production);
router.all('/reports/finisher-drawing/mix-wise',authenticate, production);
router.all('/reports/finisher-drawing/machine-wise',authenticate, production);
router.all('/reports/finisher-drawing/shift-wise',authenticate, production);
router.all('/reports/finisher-drawing/stoppage',authenticate, production);
router.all('/reports/finisher-drawing/summary',authenticate, production);
router.all('/reports/overall/employee-performance',authenticate, production);
router.all('/reports/overall/production',authenticate, production);
router.all('/reports/overall/spg-ac-packing',authenticate, production);
router.all('/reports/overall/stoppage',authenticate, production);
router.all('/reports/overall/summary',authenticate, production);
router.all('/reports/overall/supervisor',authenticate, production);
router.all('/reports/overall/ukg',authenticate, production);
router.all('/reports/overall/waste',authenticate, production);
router.all('/reports/simplex/employee-performance',authenticate, production);
router.all('/reports/simplex/machine-wise',authenticate, production);
router.all('/reports/simplex/shift-wise',authenticate, production);
router.all('/reports/simplex/stoppage',authenticate, production);
router.all('/reports/simplex/summary',authenticate, production);
router.all('/reports/spinning/count-wise',authenticate, production);
router.all('/reports/spinning/daily-end-break',authenticate, production);
router.all('/reports/spinning/employee-performance',authenticate, production);
router.all('/reports/spinning/machine-wise',authenticate, production);
router.all('/reports/spinning/shift-wise',authenticate, production);
router.all('/reports/spinning/stoppage',authenticate, production);
router.all('/reports/spinning/summary',authenticate, production);
router.all('/reports/unilap/machine-wise',authenticate, production);
router.all('/reports/unilap/stoppage',authenticate, production);
router.all('/reports/unilap/summary',authenticate, production);

export default router;
