import express from 'express';
import { report } from '../controllers/report.controller.js';

const router = express.Router();
// The exact "report/..." paths your React apiPath calls (mounted at /api/v1/report).
// Each path is forwarded to the core service by the controller.
router.all('/costing/categorywise', report);
router.all('/costing/departmentwise', report);
router.all('/costing/itemwise', report);
router.all('/costing/machinewise', report);
router.all('/grn-approval/pending', report);
router.all('/grn-bill-passing/datewise', report);
router.all('/grn-bill-passing/supplierwise', report);
router.all('/inward/categorywise', report);
router.all('/inward/datewise', report);
router.all('/inward/departmentwise', report);
router.all('/inward/itemwise', report);
router.all('/inward/supplierwise', report);
router.all('/issue/costheadwise', report);
router.all('/issue/datewise', report);
router.all('/issue/departmentwise', report);
router.all('/issue/itemwise', report);
router.all('/issue/machinewise', report);
router.all('/purchase-return/datewise', report);
router.all('/purchase-return/supplierwise', report);
router.all('/purchaseorder/categorywise', report);
router.all('/purchaseorder/costheadwise', report);
router.all('/purchaseorder/itemwise', report);
router.all('/purchaseorder/pending/categorywise', report);
router.all('/purchaseorder/pending/itemwise', report);
router.all('/purchaseorder/pending/supplierwise', report);
router.all('/purchaseorder/supplierwise', report);
router.all('/purchaseorderdetails', report);
router.all('/service-bill-passing/datewise', report);
router.all('/service-bill-passing/supplierwise', report);
router.all('/service-order/material/datewise', report);
router.all('/service-order/material/departmentwise', report);
router.all('/service-order/visitors/datewise', report);
router.all('/service-order/visitors/departmentwise', report);
router.all('/stock/departmentwise-closing', report);
router.all('/stock/departmentwise-value', report);
router.all('/stock/groupwise', report);
router.all('/yarn/agent-commission/agentwise', report);
router.all('/yarn/agent-commission/datewise', report);
router.all('/yarn/grn/datewise', report);
router.all('/yarn/production/countwise', report);
router.all('/yarn/production/datewise', report);
router.all('/yarn/production/lotnowise', report);
router.all('/yarn/purchase-order/countwise', report);
router.all('/yarn/purchase-order/datewise', report);
router.all('/yarn/purchase-order/supplierwise', report);
router.all('/yarn/sales-day-book', report);
router.all('/yarn/sales-invoice/agentwise', report);
router.all('/yarn/sales-invoice/avgrate-countwise', report);
router.all('/yarn/sales-invoice/countwise', report);
router.all('/yarn/sales-invoice/customerwise', report);
router.all('/yarn/sales-invoice/datewise', report);
router.all('/yarn/sales-order-pending/detailed', report);
router.all('/yarn/sales-order-pending/summary', report);
router.all('/yarn/sales-order/agentwise', report);
router.all('/yarn/sales-order/countwise', report);
router.all('/yarn/sales-order/customerwise', report);
router.all('/yarn/sales-order/datewise', report);
router.all('/yarn/sales-return/customerwise', report);
router.all('/yarn/sales-return/datewise', report);
router.all('/yarn/stock/count-group-wise', report);
router.all('/yarn/stock/datewise', report);
router.all('/yarn/stock/datewise-with-kgs', report);

export default router;
