import express from 'express';
import { report } from '../controllers/report.controller.js';
import { authenticate } from "../middleware/authMiddleware.js";

const router = express.Router();
// The exact "report/..." paths your React apiPath calls (mounted at /api/v1/report).
// Each path is forwarded to the core service by the controller.
router.all('/costing/categorywise',authenticate, report);
router.all('/costing/departmentwise',authenticate, report);
router.all('/costing/itemwise',authenticate, report);
router.all('/costing/machinewise',authenticate, report);
router.all('/grn-approval/pending',authenticate, report);
router.all('/grn-bill-passing/datewise',authenticate, report);
router.all('/grn-bill-passing/supplierwise',authenticate, report);
router.all('/inward/categorywise',authenticate, report);
router.all('/inward/datewise',authenticate, report);
router.all('/inward/departmentwise',authenticate, report);
router.all('/inward/itemwise',authenticate, report);
router.all('/inward/supplierwise',authenticate, report);
router.all('/issue/costheadwise',authenticate, report);
router.all('/issue/datewise',authenticate, report);
router.all('/issue/departmentwise',authenticate, report);
router.all('/issue/itemwise',authenticate, report);
router.all('/issue/machinewise',authenticate, report);
router.all('/service-bill-passing/datewise',authenticate, report);
router.all('/service-bill-passing/supplierwise',authenticate, report);
router.all('/service-order/material/datewise',authenticate, report);
router.all('/service-order/material/departmentwise',authenticate, report);
router.all('/service-order/visitors/datewise',authenticate, report);
router.all('/service-order/visitors/departmentwise',authenticate, report);
router.all('/stock/departmentwise-closing',authenticate, report);
router.all('/stock/departmentwise-value',authenticate, report);
router.all('/stock/groupwise',authenticate, report);
router.all('/yarn/agent-commission/agentwise',authenticate, report);
router.all('/yarn/agent-commission/datewise',authenticate, report);
router.all('/yarn/grn/datewise',authenticate, report);
router.all('/yarn/production/countwise',authenticate, report);
router.all('/yarn/production/datewise',authenticate, report);
router.all('/yarn/production/lotnowise',authenticate, report);
router.all('/yarn/purchase-order/countwise',authenticate, report);
router.all('/yarn/purchase-order/datewise',authenticate, report);
router.all('/yarn/purchase-order/supplierwise',authenticate, report);
router.all('/yarn/sales-day-book',authenticate, report);
router.all('/yarn/sales-invoice/agentwise',authenticate, report);
router.all('/yarn/sales-invoice/avgrate-countwise',authenticate, report);
router.all('/yarn/sales-invoice/countwise',authenticate, report);
router.all('/yarn/sales-invoice/customerwise',authenticate, report);
router.all('/yarn/sales-invoice/datewise',authenticate, report);
router.all('/yarn/sales-order-pending/detailed',authenticate, report);
router.all('/yarn/sales-order-pending/summary',authenticate, report);
router.all('/yarn/sales-order/agentwise',authenticate, report);
router.all('/yarn/sales-order/countwise',authenticate, report);
router.all('/yarn/sales-order/customerwise',authenticate, report);
router.all('/yarn/sales-order/datewise',authenticate, report);
router.all('/yarn/sales-return/customerwise',authenticate, report);
router.all('/yarn/sales-return/datewise',authenticate, report);
router.all('/yarn/sales-return',authenticate, report);
router.all('/yarn/sales-return-options',authenticate, report);
router.all('/yarn/yarn-realisation',authenticate, report);
router.all('/yarn/stock-bag',authenticate, report);
router.all('/yarn/stock-bag-options',authenticate, report);
router.all('/yarn/gate-pass',authenticate, report);
router.all('/yarn/gate-pass-options',authenticate, report);
router.all('/yarn/rg1',authenticate, report);
router.all('/yarn/rg1-options',authenticate, report);
router.all('/yarn/internal-transfer',authenticate, report);
router.all('/yarn/internal-transfer-options',authenticate, report);
router.all('/yarn/sales-day-book-details',authenticate, report);
router.all('/yarn/sales-day-book-details-options',authenticate, report);
router.all('/yarn/stock/count-group-wise',authenticate, report);
router.all('/yarn/stock/datewise',authenticate, report);
router.all('/yarn/stock/datewise-with-kgs',authenticate, report);
router.all('/yarn/master',authenticate, report);
router.all('/yarn/production',authenticate, report);
router.all('/yarn/production-options',authenticate, report);
router.all('/yarn/sales-order',authenticate, report);
router.all('/yarn/sales-order-options',authenticate, report);
router.all('/yarn/sales-order-pending',authenticate, report);
router.all('/yarn/sales-order-pending-options',authenticate, report);
router.all('/yarn/purchase-order-report',authenticate, report);
router.all('/yarn/purchase-order-report-options',authenticate, report);
router.all('/yarn/grn-report',authenticate, report);
router.all('/yarn/grn-report-options',authenticate, report);
router.all('/yarn/sales-invoice',authenticate, report);
router.all('/yarn/sales-invoice-options',authenticate, report);
router.all('/yarn/agent-commission',authenticate, report);
router.all('/yarn/agent-commission-options',authenticate, report);
router.all('/yarn/transport-invoice',authenticate, report);
router.all('/yarn/transport-invoice-options',authenticate, report);

export default router;
